# Site settings
author: Saifuddin Anjarwalla
title: 
header-img: img/home-bg.png
email: saifuddinanjarwalla@gmail.com
copyright_name: Saifuddin Anjarwalla
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  SaifuddinAnjarwalla

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
